[versions]
agp = "8.13.1"
commonsNet = "3.12.0"
smbj = "0.13.0"
kotlin = "2.2.21"
composeBom = "2025.11.00"
activityCompose = "1.12.0-rc01"
koin = "4.1.1"
lazycolumnscrollbar = "2.2.0"
nanohttpd = "2.3.1"
room = "2.8.3"
aboutLibraries = "13.1.0"
navigation3 = "1.0.0"
kotlinx-serialization = "1.9.0"
accompanist = "0.37.3"
okhttp = "5.3.0"
sardineAndroid = "0.8"
reorderable = "3.0.0"
coil = "3.3.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
sardine-android = { module = "com.github.thegrizzlylabs:sardine-android", version.ref = "sardineAndroid" }
saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version = "1.9.4" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version = "1.5.0-alpha11" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-material3-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.1.1" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics-android" }
androidx-preferences-ktx = { group = "androidx.preference", name = "preference-ktx", version = "1.2.1" }
mediasession = { group = "androidx.media", name = "media", version = "1.7.1" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version = "1.1.0" }
seeker = "com.github.abdallahmehiz:seeker:2.0.1"
material = "com.google.android.material:material:1.14.0-alpha08"
mediainfo-lib = "com.github.marlboro-advance:mediainfoAndroid:v1.0.0-fix"

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }

compose-prefs = { module = "me.zhanghai.compose.preference:preference", version = "2.1.0" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }


kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.4.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

truetype-parser = { module = "io.github.yubyf:truetypeparser-light", version = "2.1.4" }
fsaf = { module = "com.github.K1rakishou:Fuck-Storage-Access-Framework", version = "1.1.3" }

aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }

[bundles]
koin = ["koin-core", "koin-android", "koin-compose", "koin-viewmodel"]
compose-navigation3 = ["androidx-navigation3-runtime", "androidx-navigation3-ui"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version = "2.2.20-2.0.3" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }