name: CI/CD Build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate short SHA
        id: set-short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleStandardRelease

      - name: Upload app-arm64-v8a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-standard-arm64-v8a-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload app-armeabi-v7a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-standard-armeabi-v7a-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload app-universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-standard-universal-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload app-x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-standard-x86-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload app-x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-standard-x86_64-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned.apk
          if-no-files-found: warn
